/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f446xx.h"
#include "stm32f446xx_dma.h"
#include "stm32f446xx_gpio.h"
#include "stm32f446xx_i2c.h"
#include "stm32f446xx_tim.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                       \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int _write(int le, char *ptr, int len) {
  int DataIdx;
  for (DataIdx = 0; DataIdx < len; DataIdx++) {
    ITM_SendChar(*ptr++);
  }
  return len;
}

void i2c_driver_setup();

#define I2C_GPIO_PORT GPIOB
#define I2C_GPIO_SCL_PIN 8
#define I2C_GPIO_SDA_PIN 9

#define I2C_PORT I2C1
#define I2C_PORT_EV_IRQN I2C1_EV_IRQn
#define I2C_PORT_EV_IRQ_HANDLER I2C1_EV_IRQHandler
#define I2C_PORT_ERR_IRQN I2C1_ER_IRQn
#define I2C_PORT_ERR_IRQ_HANDLER I2C1_ER_IRQHandler

#define I2C_DMA_TX_PORT DMA1
#define I2C_DMA_TX_STREAM DMA1_Stream6
#define I2C_DMA_TX_CHANNEL 1
#define I2C_DMA_TX_STREAM_IRQN DMA1_Stream6_IRQn
#define I2C_DMA_TX_STREAM_IRQ_HANDLER DMA1_Stream6_IRQHandler

#define I2C_DMA_RX_PORT DMA1
#define I2C_DMA_RX_STREAM DMA1_Stream5
#define I2C_DMA_RX_CHANNEL 1
#define I2C_DMA_RX_STREAM_IRQN DMA1_Stream5_IRQn
#define I2C_DMA_RX_STREAM_IRQ_HANDLER DMA1_Stream5_IRQHandler

#define SIZEOF(arr) ((unsigned int)sizeof(arr) / sizeof(arr[0]))

#define VERY_FAST 16
#define FAST 10000
#define MEDIUM 300000
#define SLOW 1000000
#define WAIT(CNT)                                                              \
  do {                                                                         \
    for (int sleep_cnt = 0; sleep_cnt < CNT; sleep_cnt++)                      \
      ;                                                                        \
  } while (0)

/*
void setup_start_sequence_dma(void) {
  I2CDMAConfig_t dma_config = {.address = gyro_addr,
                               .tx = {.buff = tx_start_buff, .len =
SIZEOF(tx_start_buff)}, .rx = {.buff = NULL, .len = 0}, .tx_stream =
I2C_DMA_TX_STREAM, .rx_stream = I2C_DMA_RX_STREAM, .dma_set_buffer_cb =
dma_set_buffer, .dma_start_transfer_cb = dma_start_transfer, .circular =
I2C_INTERRUPT_NON_CIRCULAR, .callback = setup_main_sequence_dma};
  i2c_setup_interrupt_dma(I2C_PORT, &dma_config);
}

void setup_main_sequence_dma(void) {
  I2CDMAConfig_t dma_config = {.address = gyro_addr,
                               .tx = {.buff = tx_buff, .len = SIZEOF(tx_buff)},
                               .rx = {.buff = rx_buff, .len = SIZEOF(rx_buff)},
                               .tx_stream = I2C_DMA_TX_STREAM,
                               .rx_stream = I2C_DMA_RX_STREAM,
                               .dma_set_buffer_cb = dma_set_buffer,
                               .dma_start_transfer_cb = dma_start_transfer,
                               .circular = I2C_INTERRUPT_NON_CIRCULAR,
                               .callback = express_data};
  i2c_setup_interrupt_dma(I2C_PORT, &dma_config);
  timer_enable(TIM8);
}
*/

// START OF 1602 I2C MACROS
#define LCD_I2C_ADDR_VDD 0x27 // When A0/1/2 are all HIGH

// START OF 1602 LCD MACROS
// NOTE: Following two commands require 1520ms
#define LCD_CLEAR_DISPLAY 0x1 // CLears entire display
#define LCD_RETURN_HOME 0x2

// NOTE: Rest of commands require 37us
#define LCD_ENTRY_MODE_MASK 0x4
#define LCD_ENTRY_MODE_INC 0x2
#define LCD_ENTRY_MODE_SHIFT 0x1

#define LCD_DISPLAY_CFG_MASK 0x8
#define LCD_DISPLAY_ON_MASK 0x4
#define LCD_CURSOR_ON_MASK 0x2
#define LCD_BLINK_ON_MASK 0x1

// Might be wrong - not sure if S/C means 1/0 or 0/1
#define LCD_DISPLAY_CURSOR_LEFT 0x18
#define LCD_DISPLAY_CURSOR_RIGHT 0x1C
#define LCD_SHIFT_CURSOR_LEFT 0x10
#define LCD_SHIFT_CURSOR_RIGHT 0x14

// PRobably needs macros for function sets
#define LCD_FUNCTION_MASK 0x20
#define LCD_DATA_LENGTH_MASK 0x10
#define LCD_DISPLAY_LINES_MASK 0x8
#define LCD_CHAR_FONT_MASK 0x4

#define LCD_SET_CGRAM_ADDR_MASK 0x40
#define LCD_SET_DDRAM_ADDR_MASK 0x80

#define RS_OFF_MASK 0x0
#define RS_ON_MASK 0x1

#define RW_WRITE_MASK 0x0
#define RW_READ_MASK 0x2

#define CLOCK_HIGH_MASK 0x4
#define CLOCK_LOW_MASK 0

#define BACKLIGHT_ON_MASK 0x8
#define BACKLIGHT_OFF_MASK 0

// END OF 1602 MACROS

// typedef struct {
//   uint8_t byte;
//   int wait_length;
// } lcd_package_t;
//
int main(void) {
  i2c_driver_setup();
  WAIT(MEDIUM);
  uint8_t bytes[4];
  uint8_t upp, low;

  // Refer to page 39 of manual
  // Function set 4 bit (DB5 = 1, DB4=1, RS=0, RW=0)
  uint8_t fn_set_4b = LCD_FUNCTION_MASK;
  upp = 0xF0 & fn_set_4b;
  low = 0xF0 & (fn_set_4b << 4);

  bytes[0] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[1] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[2] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | low;

  bytes[3] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | low;

  i2c_master_send(I2C_PORT, bytes, 2, LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(MEDIUM);

  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(MEDIUM);

  // Display on (DB5-7 = 0, then DB5-7 = 1, RS/RW = 0)
  uint8_t disp_on =
      LCD_DISPLAY_CFG_MASK | LCD_DISPLAY_ON_MASK | LCD_CURSOR_ON_MASK;
  upp = 0xF0 & disp_on;
  low = 0xF0 & (disp_on << 4);

  bytes[0] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[1] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[2] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | low;

  bytes[3] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | low;

  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(MEDIUM);

  // Entry mode set (DB5-7 = 0,  then DB5-6 = 1, RS/RW=0)
  uint8_t entry_mode_set = LCD_ENTRY_MODE_MASK | LCD_ENTRY_MODE_INC;
  upp = 0XF0 & entry_mode_set;
  low = 0XF0 & (entry_mode_set << 4);

  bytes[0] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[1] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[2] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | low;

  bytes[3] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | low;

  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(MEDIUM);

  // Return home
  uint8_t ret_home = LCD_RETURN_HOME;
  upp = 0XF0 & ret_home;
  low = 0XF0 & (ret_home << 4);

  bytes[0] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[1] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | upp;

  bytes[2] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK | low;

  bytes[3] =
      RS_OFF_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK | low;

  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(MEDIUM);

  // Set DDRAM

  // Write data to CGRAM//DDRAM (RS = 1, RW = 0, )
  uint8_t test_str[] = "test";
  int len = SIZEOF(test_str);

  for (int i = 0; i < 4; i++) {
    upp = (0xF0 & test_str[i]);
    low = (0xF0 & (test_str[i] << 4));

    bytes[0] =
        upp | RS_ON_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK;

    bytes[1] =
        upp | RS_ON_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK;

    bytes[2] =
        low | RS_ON_MASK | RW_WRITE_MASK | CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK;

    bytes[3] =
        low | RS_ON_MASK | RW_WRITE_MASK | CLOCK_LOW_MASK | BACKLIGHT_ON_MASK;

    if (i == len - 1)
      i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD,
                      I2C_STOP);
    else
      i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD,
                      I2C_NO_STOP);
  }

  for (;;) {
  }
}

void i2c_driver_setup() {
  GPIO_peri_clock_control(I2C_GPIO_PORT, GPIO_CLOCK_ENABLE);
  GPIOConfig_t default_gpio_cfg = {.mode = GPIO_MODE_ALTFN,
                                   .speed = GPIO_SPEED_LOW,
                                   .float_resistor = GPIO_PUPDR_NONE,
                                   .output_type = GPIO_OP_TYPE_OPENDRAIN,
                                   .alt_func_num = 4};

  GPIOHandle_t i2c_sda_handle = {.p_GPIO_addr = I2C_GPIO_PORT,
                                 .cfg = default_gpio_cfg};
  i2c_sda_handle.cfg.pin_number = I2C_GPIO_SDA_PIN;
  GPIO_init(&i2c_sda_handle);

  GPIOHandle_t i2c_scl_handle = {.p_GPIO_addr = I2C_GPIO_PORT,
                                 .cfg = default_gpio_cfg};
  i2c_scl_handle.cfg.pin_number = I2C_GPIO_SCL_PIN;
  GPIO_init(&i2c_scl_handle);

  i2c_peri_clock_control(I2C_PORT, I2C_ENABLE);
  I2CHandle_t i2c_handle = {.addr = I2C_PORT,
                            .cfg = {.peri_clock_freq_hz = (uint32_t)16E6,
                                    .device_mode = I2C_DEVICE_MODE_MASTER,
                                    .scl_mode = I2C_SCL_MODE_SPEED_SM,
                                    .dma_enable = I2C_DISABLE,
                                    .enable_on_init = I2C_ENABLE}};
  i2c_init(&i2c_handle);
}
