/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f446xx.h"
#include "stm32f446xx_dma.h"
#include "stm32f446xx_gpio.h"
#include "stm32f446xx_i2c.h"
#include "stm32f446xx_tim.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                       \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int _write(int le, char *ptr, int len) {
  int DataIdx;
  for (DataIdx = 0; DataIdx < len; DataIdx++) {
    ITM_SendChar(*ptr++);
  }
  return len;
}

#define I2C_GPIO_PORT GPIOB
#define I2C_GPIO_SCL_PIN 8
#define I2C_GPIO_SDA_PIN 9

#define I2C_PORT I2C1
#define I2C_PORT_EV_IRQN I2C1_EV_IRQn
#define I2C_PORT_EV_IRQ_HANDLER I2C1_EV_IRQHandler
#define I2C_PORT_ERR_IRQN I2C1_ER_IRQn
#define I2C_PORT_ERR_IRQ_HANDLER I2C1_ER_IRQHandler

#define I2C_DMA_TX_PORT DMA1
#define I2C_DMA_TX_STREAM DMA1_Stream6
#define I2C_DMA_TX_CHANNEL 1
#define I2C_DMA_TX_STREAM_IRQN DMA1_Stream6_IRQn
#define I2C_DMA_TX_STREAM_IRQ_HANDLER DMA1_Stream6_IRQHandler

#define I2C_DMA_RX_PORT DMA1
#define I2C_DMA_RX_STREAM DMA1_Stream5
#define I2C_DMA_RX_CHANNEL 1
#define I2C_DMA_RX_STREAM_IRQN DMA1_Stream5_IRQn
#define I2C_DMA_RX_STREAM_IRQ_HANDLER DMA1_Stream5_IRQHandler

#define SIZEOF(arr) ((unsigned int)sizeof(arr) / sizeof(arr[0]))

#define VERY_FAST 16
#define FAST 10000
#define MEDIUM 300000
#define SLOW 1000000
#define WAIT(CNT)                                                              \
  do {                                                                         \
    for (int sleep_cnt = 0; sleep_cnt < CNT; sleep_cnt++)                      \
      ;                                                                        \
  } while (0)

/*
void setup_start_sequence_dma(void) {
  I2CDMAConfig_t dma_config = {.address = gyro_addr,
                               .tx = {.buff = tx_start_buff, .len =
SIZEOF(tx_start_buff)}, .rx = {.buff = NULL, .len = 0}, .tx_stream =
I2C_DMA_TX_STREAM, .rx_stream = I2C_DMA_RX_STREAM, .dma_set_buffer_cb =
dma_set_buffer, .dma_start_transfer_cb = dma_start_transfer, .circular =
I2C_INTERRUPT_NON_CIRCULAR, .callback = setup_main_sequence_dma};
  i2c_setup_interrupt_dma(I2C_PORT, &dma_config);
}

void setup_main_sequence_dma(void) {
  I2CDMAConfig_t dma_config = {.address = gyro_addr,
                               .tx = {.buff = tx_buff, .len = SIZEOF(tx_buff)},
                               .rx = {.buff = rx_buff, .len = SIZEOF(rx_buff)},
                               .tx_stream = I2C_DMA_TX_STREAM,
                               .rx_stream = I2C_DMA_RX_STREAM,
                               .dma_set_buffer_cb = dma_set_buffer,
                               .dma_start_transfer_cb = dma_start_transfer,
                               .circular = I2C_INTERRUPT_NON_CIRCULAR,
                               .callback = express_data};
  i2c_setup_interrupt_dma(I2C_PORT, &dma_config);
  timer_enable(TIM8);
}
*/

// START OF 1602 I2C MACROS
#define LCD_I2C_ADDR_VDD 0x27 // When A0/1/2 are all HIGH

// START OF 1602 LCD MACROS
// NOTE: Following two commands require 1520ms
#define LCD_CLEAR_DISPLAY 0x1 // CLears entire display
#define LCD_RETURN_HOME 0x2

// NOTE: Rest of commands require 37us
#define LCD_ENTRY_MODE_MASK 0x4
#define LCD_ENTRY_MODE_INC 0x2
#define LCD_ENTRY_MODE_SHIFT 0x1

#define LCD_DISPLAY_CFG_MASK 0x8
#define LCD_DISPLAY_ON_MASK 0x4
#define LCD_CURSOR_ON_MASK 0x2
#define LCD_BLINK_ON_MASK 0x1

// Might be wrong - not sure if S/C means 1/0 or 0/1
#define LCD_DISPLAY_CURSOR_LEFT 0x18
#define LCD_DISPLAY_CURSOR_RIGHT 0x1C
#define LCD_SHIFT_CURSOR_LEFT 0x10
#define LCD_SHIFT_CURSOR_RIGHT 0x14

// PRobably needs macros for function sets
#define LCD_FUNCTION_MASK 0x20
#define LCD_DATA_LENGTH_MASK 0x10
#define LCD_DISPLAY_TWO_LINES 0x8
#define LCD_CHAR_FONT_MASK 0x4

#define LCD_SET_CGRAM_ADDR_MASK 0x40
#define LCD_SET_DDRAM_ADDR_MASK 0x80

#define RS_OFF_MASK 0x0
#define RS_ON_MASK 0x1

#define RW_WRITE_MASK 0x0
#define RW_READ_MASK 0x2

#define CLOCK_HIGH_MASK 0x4
#define CLOCK_LOW_MASK 0

#define BACKLIGHT_ON_MASK 0x8
#define BACKLIGHT_OFF_MASK 0

#define JUMP_SECOND_LINE 0xC0 // Used to set DDRAM to second line

typedef enum { RS_INST_WR = 0, RS_DDR_WR = 1 } rs_type_t;

typedef struct {
  uint8_t buff[132];
  int len;
} lcd_lines_t;

lcd_lines_t lcd_lines;
uint8_t clr_home[4];

/** Function to get the bytes required to be transmitted via I2C
 * NOTE: Requires arr to be 4 elements
 * **/
void set_bytes_arr(uint8_t* arr, rs_type_t rs, uint8_t word);
void setup_lcd_chars_xmission(void);
void setup_lcd_ret_home_xmission(void);
void convert_uint32_to_str(void* arr, int capacity, uint32_t num);
void i2c_dma_setup();

// typedef struct {
//   uint8_t byte;
//   int wait_length;
// } lcd_package_t;
//
int main(void) {
  i2c_dma_setup();
  WAIT(SLOW);
  uint8_t bytes[4];

  // Refer to page 39 of manual
  // Function set 4 bit (DB5 = 1, DB4=1, RS=0, RW=0)
  uint8_t fn_set_4b = LCD_FUNCTION_MASK | LCD_DISPLAY_TWO_LINES;

  set_bytes_arr(bytes, 0, fn_set_4b);
  i2c_master_send(I2C_PORT, bytes, 2, LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(FAST);
  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(FAST);

  // Display on (DB5-7 = 0, then DB5-7 = 1, RS/RW = 0)
  uint8_t disp_on =
      LCD_DISPLAY_CFG_MASK | LCD_DISPLAY_ON_MASK | LCD_CURSOR_ON_MASK;
  set_bytes_arr(bytes, 0, disp_on);
  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(FAST);

  // Entry mode set (DB5-7 = 0,  then DB5-6 = 1, RS/RW=0)
  uint8_t entry_mode_set = LCD_ENTRY_MODE_MASK | LCD_ENTRY_MODE_INC;
  set_bytes_arr(bytes, 0, entry_mode_set);
  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(FAST);

  // Clear screen
  uint8_t clear_screen = LCD_CLEAR_DISPLAY;
  set_bytes_arr(bytes, 0, clear_screen);
  i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD, I2C_STOP);
  WAIT(SLOW);

  // Set DDRAM

  // Write data to CGRAM//DDRAM (RS = 1, RW = 0, )
  uint8_t line1[] = "asdf";
  int len1 = SIZEOF(line1);

  for (int i = 0; i < 4; i++) {

    set_bytes_arr(bytes, 1, line1[i]);

    if (i == len1 - 1)
      i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD,
                      I2C_STOP);
    else
      i2c_master_send(I2C_PORT, bytes, SIZEOF(bytes), LCD_I2C_ADDR_VDD,
                      I2C_NO_STOP);
  }

  NVIC_EnableIRQ(I2C_DMA_TX_STREAM_IRQN);
  NVIC_EnableIRQ(I2C_PORT_EV_IRQN);
  NVIC_EnableIRQ(I2C_PORT_ERR_IRQN);

  for (;;) {
  }
}

/** Function to get the bytes required to be transmitted via I2C
 * NOTE: Requires arr to be 4 elements
 * **/
void set_bytes_arr(uint8_t *arr, uint8_t rs, uint8_t word) {
  uint8_t rs_mask = (rs == 1) ? RS_ON_MASK : RS_OFF_MASK;
  uint8_t upp = (0xF0 & word);
  uint8_t low = (0xF0 & (word << 4));

  uint8_t clk_hi = CLOCK_HIGH_MASK | BACKLIGHT_ON_MASK;
  uint8_t clk_lo = CLOCK_LOW_MASK | BACKLIGHT_ON_MASK;

  arr[0] = upp | rs_mask | clk_hi;
  arr[1] = upp | rs_mask | clk_lo;
  arr[2] = low | rs_mask | clk_hi;
  arr[3] = low | rs_mask | clk_lo;
}

void convert_uint32_to_str(void *arr, int capacity, uint32_t num) {
  int lsd_index = 10;
  if (capacity < 10)
    lsd_index = capacity; // max uint32_t number has 10 digits

  while (lsd_index > 0) {
    const int i = lsd_index - 1;

    if (num > 0 || lsd_index == capacity) {
      ((uint8_t *)arr)[i] = '0' + (num % 10);
      num = num / 10;
    } else {
      ((uint8_t *)arr)[i] = ' ';
    }

    lsd_index--;
  }
}

void I2C_PORT_EV_IRQ_HANDLER(void) { i2c_dma_irq_handling_start(I2C_PORT); }

void I2C_PORT_ERR_IRQ_HANDLER(void) {
  I2CIRQType_t irq_error = i2c_irq_error_handling(I2C1);
  if (irq_error == I2C_IRQ_TYPE_ERROR_ACKFAIL) {
    printf("Error...\n");
    i2c_start_interrupt_dma(I2C1);
  }
}

void i2c_dma_setup() {
  GPIO_peri_clock_control(I2C_GPIO_PORT, GPIO_CLOCK_ENABLE);
  GPIOConfig_t default_gpio_cfg = {.mode = GPIO_MODE_ALTFN,
                                   .speed = GPIO_SPEED_MEDIUM,
                                   .float_resistor = GPIO_PUPDR_NONE,
                                   .output_type = GPIO_OP_TYPE_OPENDRAIN,
                                   .alt_func_num = 4};

  GPIOHandle_t i2c_sda_handle = {.p_GPIO_addr = I2C_GPIO_PORT,
                                 .cfg = default_gpio_cfg};
  i2c_sda_handle.cfg.pin_number = I2C_GPIO_SDA_PIN;
  GPIO_init(&i2c_sda_handle);

  GPIOHandle_t i2c_scl_handle = {.p_GPIO_addr = I2C_GPIO_PORT,
                                 .cfg = default_gpio_cfg};
  i2c_scl_handle.cfg.pin_number = I2C_GPIO_SCL_PIN;
  GPIO_init(&i2c_scl_handle);

  dma_peri_clock_control(I2C_DMA_TX_PORT, DMA_ENABLE);
  DMAHandle_t dma_tx_handle = {
      .stream_addr = I2C_DMA_TX_STREAM,
      .cfg = {.in = {.addr = NULL,
                     .type = DMA_IO_TYPE_MEMORY,
                     .inc = DMA_IO_ARR_INCREMENT},
              .out = {.addr = &I2C_PORT->DR,
                      .type = DMA_IO_TYPE_PERIPHERAL,
                      .inc = DMA_IO_ARR_STATIC},
              .mem_data_size = DMA_DATA_SIZE_8_BIT,
              .peri_data_size = DMA_DATA_SIZE_8_BIT,
              .dma_elements = 0,
              .channel = I2C_DMA_TX_CHANNEL,
              .priority = DMA_PRIORITY_HIGH,
              .circ_buffer = DMA_BUFFER_FINITE,
              .flow_control = DMA_PERIPH_NO_FLOW_CONTROL,
              .interrupt_en =
                  {
                      .direct_mode_error = DMA_DISABLE,
                      .transfer_error = DMA_DISABLE,
                      .full_transfer = DMA_ENABLE,
                      .half_transfer = DMA_DISABLE,
                  },
              .start_enabled = DMA_DISABLE},
  };
  dma_stream_init(&dma_tx_handle);

  i2c_peri_clock_control(I2C_PORT, I2C_ENABLE);
  I2CHandle_t i2c_handle = {.addr = I2C_PORT,
                            .cfg = {.peri_clock_freq_hz = (uint32_t)16E6,
                                    .device_mode = I2C_DEVICE_MODE_MASTER,
                                    .scl_mode = I2C_SCL_MODE_SPEED_SM,
                                    .interrupt_enable = I2C_ENABLE,
                                    .dma_enable = I2C_DISABLE,
                                    .enable_on_init = I2C_ENABLE}};
  i2c_init(&i2c_handle);
}

void setup_lcd_chars_xmission(void) {
  I2CDMAConfig_t dma_config = {
      .address = LCD_I2C_ADDR_VDD,
      .tx = {.buff = lcd_lines.buff, .len = lcd_lines.len},
      .rx = {.buff = NULL, .len = 0},
      .tx_stream = I2C_DMA_TX_STREAM,
      .dma_set_buffer_cb = dma_set_buffer,
      .dma_start_transfer_cb = dma_start_transfer,
      .circular = I2C_INTERRUPT_NON_CIRCULAR,
      .callback = NULL};
  i2c_setup_interrupt_dma(I2C_PORT, &dma_config);
}

void setup_lcd_ret_home_xmission(void) {
  I2CDMAConfig_t dma_config = {
      .address = LCD_I2C_ADDR_VDD,
      .tx = {.buff = ret_home, .len = SIZEOF(ret_home)},
      .rx = {.buff = NULL, .len = 0},
      .tx_stream = I2C_DMA_TX_STREAM,
      .dma_set_buffer_cb = dma_set_buffer,
      .dma_start_transfer_cb = dma_start_transfer,
      .circular = I2C_INTERRUPT_NON_CIRCULAR,
      .callback = NULL};
  i2c_setup_interrupt_dma(I2C_PORT, &dma_config);
}
